server:
    port: 8080
    servlet:
      encoding:
        charset: UTF-8
        force: true

spring:
  application:
    name: SBB

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true # 자동 리로딩

  ####################################
  # MySQL ??
  ####################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/c_ban?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root1234

  ####################################
  # JPA ??
  ####################################
  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: update      # create, update, ... /  create : 실행할 때마다 새로 생성, update : 정보 유지
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # ?????? ?????? ??  myName <--> my_name
    show-sql: true          # SQL ?? ??
    properties:
      hibernate:
        format_sql: true    # SQL ??? ??